services:
  - type: web
    name: escola-conecta-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: escola-conecta-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://agenda-escolar-1-55fo.onrender.com
  - type: web
    name: escola-conecta-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://agenda-escolar-api-aym3.onrender.com
databases:
  - name: escola-conecta-db
    databaseName: schoolhub
    user: schoolhub
